#!/bin/sh

# Check connection every 10 seconds, and after 3 tries (30 seconds), drop and
# let autossh re-connect.
ServerAliveInterval="5"
ServerAliveCountMax="3"
StrictHostKeyChecking="no"
LocalUser="root"
IdentityFile="~/.ssh/id_rsa"
AUTOSSH_LOGFILE="/var/log/autossh.log" 
RemoteUser="visu"
RemoteHost="h2o-protec.de"
RemotePort="22"

# Array of ports to be forwarded:
ForwardPort=(
    "R 127.0.0.1:10000:127.0.0.1:22"
    "R 127.0.0.1:2000:127.0.0.1:80"
)
